[package]
name = "petrol-bot"
version = "0.1.0"
authors = ["Raclett3 <im@s283.net>"]
edition = "2018"

[dependencies]
serenity = {version = "0.9.0-rc.1", default-features = false, features = ["client", "gateway", "rustls_backend", "model"]}
tokio = {version = "0.2", features = ["macros"]}
